//! Geometric realization of the spectre tiling.
//!
//! Every hexagon of the marked-hexagon system corresponds to one actual
//! 14-sided spectre tile — except Γ, which carries two (the "mystic" pair;
//! the second one is the rare odd-orientation spectre).  There is no linear
//! map from hex-grid positions to spectre positions: geometry is propagated
//! tile-to-tile by gluing, walking the combinatorial structure.
//!
//! The transition tables come from Simon Tatham's puzzle collection
//! (`spectre-tables-auto.h`, generated by his `spectre-gen.c`), whose
//! conventions provably match ours: his child layout, child types and child
//! orientations per supertile equal `SUPERTILE_CHILDREN` exactly, so his
//! per-type base orientations coincide with ours and his hexagon edge `j`
//! is our direction `(j + 2) % 6` in the hexagon's base frame, uniformly.
//!
//! Vertices live in ℤ[d], d = exp(iπ/6), so all coordinates are exact.

use crate::hex::{DIRECTIONS, Hex};

/// Point of the plane as an integer combination of {1, d, d², d³} where
/// d = exp(iπ/6) (a 30° rotation); d⁴ = d² − 1.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct Zd(pub [i32; 4]);

impl Zd {
    pub const ZERO: Zd = Zd([0, 0, 0, 0]);
    pub const ONE: Zd = Zd([1, 0, 0, 0]);

    /// Multiply by d (rotate 30° counterclockwise).
    fn mul_d(self) -> Zd {
        let [a, b, c, e] = self.0;
        Zd([-e, a, b + e, c])
    }

    /// Rotate by `s` steps of 30° counterclockwise.
    pub fn rot30(self, s: i32) -> Zd {
        let mut r = self;
        for _ in 0..s.rem_euclid(12) {
            r = r.mul_d();
        }
        r
    }

    /// Cartesian coordinates, y pointing up.
    pub fn to_xy(self) -> (f64, f64) {
        let [a, b, c, e] = self.0;
        let h = 3f64.sqrt() / 2.0;
        (
            a as f64 + b as f64 * h + c as f64 * 0.5,
            e as f64 + b as f64 * 0.5 + c as f64 * h,
        )
    }
}

impl std::ops::Add for Zd {
    type Output = Zd;
    fn add(self, rhs: Zd) -> Zd {
        Zd(std::array::from_fn(|i| self.0[i] + rhs.0[i]))
    }
}

impl std::ops::Sub for Zd {
    type Output = Zd;
    fn sub(self, rhs: Zd) -> Zd {
        Zd(std::array::from_fn(|i| self.0[i] - rhs.0[i]))
    }
}

/// Turn at each spectre vertex, in 30° steps (Tatham's `spectre_angles`).
/// All 14 edges are unit length; the sum is −12, i.e. one clockwise turn.
const SPECTRE_ANGLES: [i32; 14] = [-3, -2, 3, -2, -3, 2, -3, 2, -3, -2, 0, -2, 3, -2];

/// All 14 vertices of a spectre, given vertices `u` and `v` of its edge
/// `index_of_u` (edge `i` runs from vertex `i` to vertex `i + 1`).  The
/// shape is rigid, so one edge determines the rest.
pub fn spectre_place(u: Zd, v: Zd, index_of_u: usize) -> [Zd; 14] {
    let mut verts = [Zd::ZERO; 14];
    let mut p = u;
    let mut disp = v - u;
    for i in 0..14 {
        verts[(i + index_of_u) % 14] = p;
        p = p + disp;
        disp = disp.rot30(SPECTRE_ANGLES[(i + 1 + index_of_u) % 14]);
    }
    verts
}

/// Ear-clip triangulation of the (concave) spectre by vertex index — valid
/// for every rigid placement, since the tiling never mirrors the tile.
pub const SPECTRE_TRIANGLES: [[usize; 3]; 12] = [
    [13, 0, 1],
    [13, 1, 2],
    [2, 3, 4],
    [13, 2, 4],
    [13, 4, 5],
    [13, 5, 6],
    [7, 8, 9],
    [7, 9, 10],
    [6, 7, 10],
    [6, 10, 11],
    [6, 11, 12],
    [6, 12, 13],
];

/// Number of spectres a hexagon of type `t` carries.
pub fn num_spectres(t: u8) -> u8 {
    if t == 0 { 2 } else { 1 }
}

/// One cell of the spectre transition maps (Tatham's `struct MapEntry`).
///
/// In `SPECMAP` (keyed by the spectre edge being crossed): if `internal`,
/// the move stays within the same hexagon — `hi` is the destination spectre
/// index and `lo` its entry edge (only happens inside Γ's pair).  Otherwise
/// the move leaves the hexagon by its edge `hi` (Tatham numbering: our base
/// direction `(hi + 2) % 6`) at position `lo` within that edge's boundary
/// segment.
///
/// In `SPECIN` (keyed by boundary position, via `SPECEDGES`): if `internal`,
/// entering here lands on edge `lo` of spectre `hi`.  Otherwise the entry
/// point is on the Σ spur and bounces straight back out by hexagon edge `hi`
/// at position `lo`.
#[derive(Debug, Clone, Copy)]
pub struct MapEntry {
    pub internal: bool,
    pub hi: u8,
    pub lo: u8,
}

/// Boundary segment of one hexagon edge: `len` spectre edges starting at
/// `start` in the type's `SPECIN` table, in boundary-walk order.  Two glued
/// hexagon edges traverse the shared segment in opposite orders.
#[derive(Debug, Clone, Copy)]
pub struct MapEdge {
    pub start: u8,
    pub len: u8,
}

const fn m(internal: bool, hi: u8, lo: u8) -> MapEntry {
    MapEntry { internal, hi, lo }
}

const fn e(start: u8, len: u8) -> MapEdge {
    MapEdge { start, len }
}

// Tables generated from Tatham's spectre-tables-auto.h; type order
// G D J L X P S F Y = Γ Δ Θ Λ Ξ Π Σ Φ Ψ matches BASE_TILES / TILE_NAMES.

// Γ
#[rustfmt::skip]
const SPECMAP_G: [MapEntry; 28] = [
    m(false, 2, 2), m(false, 2, 1), m(false, 2, 0), m(false, 1, 2), m(false, 1, 1),
    m(false, 1, 0), m(false, 0, 2), m(false, 0, 1), m(false, 0, 0), m(false, 5, 2),
    m(true, 1, 7), m(true, 1, 6), m(true, 1, 5), m(true, 1, 4), m(false, 4, 1), m(false, 4, 0),
    m(false, 3, 1), m(false, 3, 0), m(true, 0, 13), m(true, 0, 12), m(true, 0, 11),
    m(true, 0, 10), m(false, 5, 1), m(false, 5, 0), m(false, 4, 5), m(false, 4, 4),
    m(false, 4, 3), m(false, 4, 2),
];
const SPECEDGES_G: [MapEdge; 6] = [e(0, 3), e(3, 3), e(6, 3), e(9, 2), e(11, 6), e(17, 3)];
#[rustfmt::skip]
const SPECIN_G: [MapEntry; 20] = [
    m(true, 0, 8), m(true, 0, 7), m(true, 0, 6), m(true, 0, 5), m(true, 0, 4), m(true, 0, 3),
    m(true, 0, 2), m(true, 0, 1), m(true, 0, 0), m(true, 1, 3), m(true, 1, 2), m(true, 1, 1),
    m(true, 1, 0), m(true, 1, 13), m(true, 1, 12), m(true, 1, 11), m(true, 1, 10),
    m(true, 1, 9), m(true, 1, 8), m(true, 0, 9),
];
// Δ
#[rustfmt::skip]
const SPECMAP_D: [MapEntry; 14] = [
    m(false, 3, 0), m(false, 2, 2), m(false, 2, 1), m(false, 2, 0), m(false, 1, 1),
    m(false, 1, 0), m(false, 0, 1), m(false, 0, 0), m(false, 5, 1), m(false, 5, 0),
    m(false, 4, 2), m(false, 4, 1), m(false, 4, 0), m(false, 3, 1),
];
const SPECEDGES_D: [MapEdge; 6] = [e(0, 2), e(2, 2), e(4, 3), e(7, 2), e(9, 3), e(12, 2)];
#[rustfmt::skip]
const SPECIN_D: [MapEntry; 14] = [
    m(true, 0, 7), m(true, 0, 6), m(true, 0, 5), m(true, 0, 4), m(true, 0, 3), m(true, 0, 2),
    m(true, 0, 1), m(true, 0, 0), m(true, 0, 13), m(true, 0, 12), m(true, 0, 11),
    m(true, 0, 10), m(true, 0, 9), m(true, 0, 8),
];
// Θ
#[rustfmt::skip]
const SPECMAP_J: [MapEntry; 14] = [
    m(false, 3, 0), m(false, 2, 2), m(false, 2, 1), m(false, 2, 0), m(false, 1, 1),
    m(false, 1, 0), m(false, 0, 2), m(false, 0, 1), m(false, 0, 0), m(false, 5, 1),
    m(false, 5, 0), m(false, 4, 2), m(false, 4, 1), m(false, 4, 0),
];
const SPECEDGES_J: [MapEdge; 6] = [e(0, 3), e(3, 2), e(5, 3), e(8, 1), e(9, 3), e(12, 2)];
#[rustfmt::skip]
const SPECIN_J: [MapEntry; 14] = [
    m(true, 0, 8), m(true, 0, 7), m(true, 0, 6), m(true, 0, 5), m(true, 0, 4), m(true, 0, 3),
    m(true, 0, 2), m(true, 0, 1), m(true, 0, 0), m(true, 0, 13), m(true, 0, 12),
    m(true, 0, 11), m(true, 0, 10), m(true, 0, 9),
];
// Λ
#[rustfmt::skip]
const SPECMAP_L: [MapEntry; 14] = [
    m(false, 3, 0), m(false, 2, 2), m(false, 2, 1), m(false, 2, 0), m(false, 1, 1),
    m(false, 1, 0), m(false, 0, 2), m(false, 0, 1), m(false, 0, 0), m(false, 5, 0),
    m(false, 4, 2), m(false, 4, 1), m(false, 4, 0), m(false, 3, 1),
];
const SPECEDGES_L: [MapEdge; 6] = [e(0, 3), e(3, 2), e(5, 3), e(8, 2), e(10, 3), e(13, 1)];
#[rustfmt::skip]
const SPECIN_L: [MapEntry; 14] = [
    m(true, 0, 8), m(true, 0, 7), m(true, 0, 6), m(true, 0, 5), m(true, 0, 4), m(true, 0, 3),
    m(true, 0, 2), m(true, 0, 1), m(true, 0, 0), m(true, 0, 13), m(true, 0, 12),
    m(true, 0, 11), m(true, 0, 10), m(true, 0, 9),
];
// Ξ
#[rustfmt::skip]
const SPECMAP_X: [MapEntry; 14] = [
    m(false, 3, 0), m(false, 2, 1), m(false, 2, 0), m(false, 1, 2), m(false, 1, 1),
    m(false, 1, 0), m(false, 0, 2), m(false, 0, 1), m(false, 0, 0), m(false, 5, 1),
    m(false, 5, 0), m(false, 4, 2), m(false, 4, 1), m(false, 4, 0),
];
const SPECEDGES_X: [MapEdge; 6] = [e(0, 3), e(3, 3), e(6, 2), e(8, 1), e(9, 3), e(12, 2)];
#[rustfmt::skip]
const SPECIN_X: [MapEntry; 14] = [
    m(true, 0, 8), m(true, 0, 7), m(true, 0, 6), m(true, 0, 5), m(true, 0, 4), m(true, 0, 3),
    m(true, 0, 2), m(true, 0, 1), m(true, 0, 0), m(true, 0, 13), m(true, 0, 12),
    m(true, 0, 11), m(true, 0, 10), m(true, 0, 9),
];
// Π
#[rustfmt::skip]
const SPECMAP_P: [MapEntry; 14] = [
    m(false, 3, 0), m(false, 2, 1), m(false, 2, 0), m(false, 1, 2), m(false, 1, 1),
    m(false, 1, 0), m(false, 0, 2), m(false, 0, 1), m(false, 0, 0), m(false, 5, 0),
    m(false, 4, 2), m(false, 4, 1), m(false, 4, 0), m(false, 3, 1),
];
const SPECEDGES_P: [MapEdge; 6] = [e(0, 3), e(3, 3), e(6, 2), e(8, 2), e(10, 3), e(13, 1)];
#[rustfmt::skip]
const SPECIN_P: [MapEntry; 14] = [
    m(true, 0, 8), m(true, 0, 7), m(true, 0, 6), m(true, 0, 5), m(true, 0, 4), m(true, 0, 3),
    m(true, 0, 2), m(true, 0, 1), m(true, 0, 0), m(true, 0, 13), m(true, 0, 12),
    m(true, 0, 11), m(true, 0, 10), m(true, 0, 9),
];
// Σ — its boundary has a four-edge spur (positions 4–7 of edge 0's segment
// and positions 0–1 of edge 1's): entering there bounces straight back out.
#[rustfmt::skip]
const SPECMAP_S: [MapEntry; 14] = [
    m(false, 3, 0), m(false, 2, 2), m(false, 2, 1), m(false, 2, 0), m(false, 0, 3),
    m(false, 0, 2), m(false, 0, 1), m(false, 0, 0), m(false, 5, 1), m(false, 5, 0),
    m(false, 4, 2), m(false, 4, 1), m(false, 4, 0), m(false, 3, 1),
];
const SPECEDGES_S: [MapEdge; 6] = [e(0, 6), e(6, 2), e(8, 3), e(11, 2), e(13, 3), e(16, 2)];
#[rustfmt::skip]
const SPECIN_S: [MapEntry; 18] = [
    m(true, 0, 7), m(true, 0, 6), m(true, 0, 5), m(true, 0, 4), m(false, 1, 1), m(false, 1, 0),
    m(false, 0, 5), m(false, 0, 4), m(true, 0, 3), m(true, 0, 2), m(true, 0, 1), m(true, 0, 0),
    m(true, 0, 13), m(true, 0, 12), m(true, 0, 11), m(true, 0, 10), m(true, 0, 9),
    m(true, 0, 8),
];
// Φ
#[rustfmt::skip]
const SPECMAP_F: [MapEntry; 14] = [
    m(false, 3, 0), m(false, 2, 2), m(false, 2, 1), m(false, 2, 0), m(false, 1, 1),
    m(false, 1, 0), m(false, 0, 2), m(false, 0, 1), m(false, 0, 0), m(false, 5, 1),
    m(false, 5, 0), m(false, 4, 1), m(false, 4, 0), m(false, 3, 1),
];
const SPECEDGES_F: [MapEdge; 6] = [e(0, 3), e(3, 2), e(5, 3), e(8, 2), e(10, 2), e(12, 2)];
#[rustfmt::skip]
const SPECIN_F: [MapEntry; 14] = [
    m(true, 0, 8), m(true, 0, 7), m(true, 0, 6), m(true, 0, 5), m(true, 0, 4), m(true, 0, 3),
    m(true, 0, 2), m(true, 0, 1), m(true, 0, 0), m(true, 0, 13), m(true, 0, 12),
    m(true, 0, 11), m(true, 0, 10), m(true, 0, 9),
];
// Ψ
#[rustfmt::skip]
const SPECMAP_Y: [MapEntry; 14] = [
    m(false, 3, 0), m(false, 2, 1), m(false, 2, 0), m(false, 1, 2), m(false, 1, 1),
    m(false, 1, 0), m(false, 0, 2), m(false, 0, 1), m(false, 0, 0), m(false, 5, 1),
    m(false, 5, 0), m(false, 4, 1), m(false, 4, 0), m(false, 3, 1),
];
const SPECEDGES_Y: [MapEdge; 6] = [e(0, 3), e(3, 3), e(6, 2), e(8, 2), e(10, 2), e(12, 2)];
#[rustfmt::skip]
const SPECIN_Y: [MapEntry; 14] = [
    m(true, 0, 8), m(true, 0, 7), m(true, 0, 6), m(true, 0, 5), m(true, 0, 4), m(true, 0, 3),
    m(true, 0, 2), m(true, 0, 1), m(true, 0, 0), m(true, 0, 13), m(true, 0, 12),
    m(true, 0, 11), m(true, 0, 10), m(true, 0, 9),
];

/// `SPECMAP[t][14 * spectre_index + spectre_edge]` — what crossing that
/// spectre edge does, for a type-`t` hexagon in its base orientation.
pub const SPECMAP: [&[MapEntry]; 9] = [
    &SPECMAP_G, &SPECMAP_D, &SPECMAP_J, &SPECMAP_L, &SPECMAP_X, &SPECMAP_P, &SPECMAP_S, &SPECMAP_F,
    &SPECMAP_Y,
];

/// `SPECEDGES[t][j]` — boundary segment of hexagon edge `j` (Tatham
/// numbering) of a type-`t` hexagon.
#[rustfmt::skip]
pub const SPECEDGES: [&[MapEdge; 6]; 9] = [
    &SPECEDGES_G, &SPECEDGES_D, &SPECEDGES_J, &SPECEDGES_L, &SPECEDGES_X, &SPECEDGES_P,
    &SPECEDGES_S, &SPECEDGES_F, &SPECEDGES_Y,
];

/// `SPECIN[t]` — entry table indexed via [`SPECEDGES`].
pub const SPECIN: [&[MapEntry]; 9] = [
    &SPECIN_G, &SPECIN_D, &SPECIN_J, &SPECIN_L, &SPECIN_X, &SPECIN_P, &SPECIN_S, &SPECIN_F,
    &SPECIN_Y,
];

/// Tatham's hexagon edge number for our base-frame direction `delta`.
pub fn tatham_edge(delta: usize) -> usize {
    (delta + 4) % 6
}

/// Our base-frame direction for Tatham's hexagon edge number `j`.
pub fn our_direction(j: usize) -> usize {
    (j + 2) % 6
}

/// Cross edge `edge` of spectre `index` of the hexagon at `hex` (whose
/// `(type, world rotation)` is `start`).  `tile_at(from, w)` must give the
/// `(type, world rotation)` of the hexagon at `from + DIRECTIONS[w]`, or
/// `None` outside the patch.  Returns the destination spectre as
/// `(hexagon, spectre index, entry edge)`; `None` when the move leaves the
/// patch.  Mirrors Tatham's `spectrectx_step`, with our transducer-driven
/// hexagon adjacency in place of his hexagon coordinate algorithm.
pub fn spectre_step(
    mut hex: Hex,
    start: (u8, u8),
    index: u8,
    edge: u8,
    tile_at: &mut dyn FnMut(Hex, usize) -> Option<(u8, u8)>,
) -> Option<(Hex, u8, u8)> {
    let (t, mut rot) = start;
    let mut m = SPECMAP[t as usize][14 * index as usize + edge as usize];
    while !m.internal {
        // Leave this hexagon by edge m.hi (own base frame) — world
        // direction w — and re-enter the neighbor's boundary segment at the
        // reversed position.  A non-internal entry there is the Σ spur:
        // bounce straight out again.
        let w = (our_direction(m.hi as usize) + rot as usize) % 6;
        let (t2, rot2) = tile_at(hex, w)?;
        hex = hex + DIRECTIONS[w];
        let back = (w + 9 - rot2 as usize) % 6;
        let me = SPECEDGES[t2 as usize][tatham_edge(back)];
        m = SPECIN[t2 as usize][(me.start + me.len - 1 - m.lo) as usize];
        rot = rot2;
    }
    Some((hex, m.hi, m.lo))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tree_coords::{canonical_patch_paths, edge_adjacency, path_rotation, types_along};
    use std::collections::{HashMap, VecDeque};

    /// The outline closes, all 14 edges are unit length, and every vertex
    /// angle is the prescribed multiple of 30°.
    #[test]
    fn outline_is_closed_unit_14_gon() {
        let v = spectre_place(Zd::ZERO, Zd::ONE, 0);
        for i in 0..14 {
            let (ax, ay) = v[i].to_xy();
            let (bx, by) = v[(i + 1) % 14].to_xy();
            let len2 = (bx - ax).powi(2) + (by - ay).powi(2);
            assert!((len2 - 1.0).abs() < 1e-9, "edge {i} not unit");
        }
        // Placing from any other edge of the same two vertices reproduces a
        // rotation of the same shape (sanity of the index_of_u walk).
        for k in 0..14 {
            let w = spectre_place(v[k], v[(k + 1) % 14], k);
            assert_eq!(w, v, "re-placing from edge {k} changed the polygon");
        }
    }

    /// Glued hexagon edges must carry equally many spectre boundary edges.
    /// The pairing comes from the marked-tile edge adjacency, the lengths
    /// from Tatham's tables — agreement pins the convention translation.
    #[test]
    fn segment_lengths_match_edge_adjacency() {
        for (&(t1, d1), partners) in edge_adjacency() {
            for &(t2, d2) in partners {
                let l1 = SPECEDGES[t1 as usize][tatham_edge(d1 as usize)].len;
                let l2 = SPECEDGES[t2 as usize][tatham_edge(d2 as usize)].len;
                assert_eq!(
                    l1, l2,
                    "boundary length mismatch: ({t1},{d1}) [{l1}] ~ ({t2},{d2}) [{l2}]",
                );
            }
        }
    }

    /// Generate all spectres of a canonical patch by BFS gluing and check
    /// global consistency: every spectre reached by several routes gets the
    /// same placement, every step reciprocates, and the count is one
    /// spectre per hexagon plus one extra per Γ.
    fn check_patch_spectres(top: u8, depth: usize) {
        let (_, paths) = canonical_patch_paths(top, depth);
        let tiles: HashMap<Hex, (u8, u8)> = paths
            .iter()
            .map(|(&h, c)| {
                let t = *types_along(top, &c.path).last().unwrap();
                (h, (t, path_rotation(top, &c.path)))
            })
            .collect();
        let mut tile_at = |from: Hex, w: usize| tiles.get(&(from + DIRECTIONS[w])).copied();

        let seed = Hex::new(0, 0);
        let mut placed: HashMap<(Hex, u8), [Zd; 14]> = HashMap::new();
        placed.insert((seed, 0), spectre_place(Zd::ZERO, Zd::ONE, 0));
        let mut queue = VecDeque::from([(seed, 0u8)]);
        while let Some((hex, idx)) = queue.pop_front() {
            let poly = placed[&(hex, idx)];
            let start = tiles[&hex];
            for edge in 0..14u8 {
                let Some((h2, i2, e2)) = spectre_step(hex, start, idx, edge, &mut tile_at) else {
                    continue;
                };
                // Reciprocity: stepping back returns here across `edge`.
                assert_eq!(
                    spectre_step(h2, tiles[&h2], i2, e2, &mut tile_at),
                    Some((hex, idx, edge)),
                    "top {top}: not reciprocal from {hex:?}#{idx} edge {edge}",
                );
                let p2 = spectre_place(
                    poly[(edge as usize + 1) % 14],
                    poly[edge as usize],
                    e2 as usize,
                );
                match placed.get(&(h2, i2)) {
                    Some(prev) => {
                        assert_eq!(*prev, p2, "top {top}: conflicting placement of {h2:?}#{i2}",)
                    }
                    None => {
                        placed.insert((h2, i2), p2);
                        queue.push_back((h2, i2));
                    }
                }
            }
        }

        let expected: usize = tiles.values().map(|&(t, _)| num_spectres(t) as usize).sum();
        assert_eq!(placed.len(), expected, "top {top} depth {depth}: count");
    }

    #[test]
    fn patch_spectres_consistent_depth_2_all_tops() {
        for top in 0..9 {
            check_patch_spectres(top, 2);
        }
    }

    #[test]
    fn patch_spectres_consistent_depth_3_gamma_sigma() {
        check_patch_spectres(0, 3);
        check_patch_spectres(6, 3);
    }
}
